# Generated by Django 2.0.1 on 2018-12-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_page', '0002_auto_20181219_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='path',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='peta',
            name='path',
            field=models.FileField(upload_to=''),
        ),
    ]
