# Generated by Django 2.0.1 on 2019-01-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_page', '0003_auto_20181220_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='path',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
